name: swd_mobile
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  one_context: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik/Aeonik-Bold.otf
        - asset: assets/fonts/Aeonik/Aeonik-BoldItalic.otf
        - asset: assets/fonts/Aeonik/Aeonik-Light.otf
        - asset: assets/fonts/Aeonik/Aeonik-LightItalic.otf
        - asset: assets/fonts/Aeonik/Aeonik-Regular.otf
        - asset: assets/fonts/Aeonik/Aeonik-RegularItalic.otf
          style: italic
